name: Build netcdf and Trilinos docker images
on: 
  push:
  pull_request:

jobs:
  # Label of the container job
  build-images:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build hdf5 and netcdf
        uses: docker/build-push-action@v2
        with:
          context: netcdf
          file: netcdf/Dockerfile
          push: ${{ github.event_name != 'pull_request' }} 
          tags: |
            peridigm/netcdf:latest
            peridigm/netcdf:largefiles
      - name: Build Trilinos
        if: succeeded()
        uses: docker/build-push-action@v2
        with:
          context: trilinos
          file: trilinos/Dockerfile
          push: ${{ github.event_name != 'pull_request' }} 
          tags: peridigm/trilinos:latest
      - name: Trigger rebuild of Peridigm image
        if: succeeded()
        shell: bash -l {0}
        run: |
          curl --request POST \
          --url 'https://api.github.com/repos/peridigm/peridigm/dispatches' \
          --header 'authorization: Bearer ${{secrets.PERIDIGM_SECRET_TOKEN}}' \
          --data '{"event_type": "trigger"}'
